# Ensure main app uses port 8080 (default)                                                                                                              ?
quarkus.http.port=8080
%test.quarkus.http.test-port=8080

# Ollama Configuration
quarkus.langchain4j.ollama.base-url=http://localhost:11434
quarkus.langchain4j.ollama.chat-model.model-id=mistral
quarkus.langchain4j.ollama.chat-model.log-requests=true
quarkus.langchain4j.ollama.chat-model.log-responses=true
quarkus.langchain4j.ollama.chat-model.temperature=0.0
quarkus.langchain4j.ollama.timeout=120s
quarkus.langchain4j.pgvector.dimension=384
rag.location=src/main/resources/rag
quarkus.langchain4j.embedding-model.provider=dev.langchain4j.model.embedding.onnx.bgesmallenq.BgeSmallEnQuantizedEmbeddingModel

quarkus.langchain4j.mcp.weather.transport-type=http
quarkus.langchain4j.mcp.weather.url=http://localhost:8081/mcp/sse/

# OPA Policy Configuration
# Path to the OPA WASM policy file (relative to classpath resources)
opa.policy.path=/policies/prompt-injection.wasm

#Observability
quarkus.datasource.jdbc.telemetry=true
quarkus.otel.logs.enabled=true
quarkus.otel.traces.enabled=true
%test.quarkus.observability.enabled=true
quarkus.otel.exporter.otlp.traces.headers=authorization=Bearer my_secret 
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n  
